#ifndef EMPR_LIB_I2C_ADDRESSES_H
#define EMPR_LIB_I2C_ADDRESSES_H

#define EMPR_LIB_I2C_ADDRESS_LCD 0x3b
#define EMPR_LIB_I2C_ADDRESS_KEYPAD 0x21
#define EMPR_LIB_I2C_ADDRESS_EIGHT_SEGMENT_DISPLAY 0x38

#endif
